server:
  port: 8077

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: workFlow-8077
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.17.206:8848
        namespace: public
  redis:
    database: 1
    host: 101.34.17.206
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-wait: 3000
        min-idle: 8
        max-idle: 16
        max-active: 16